import = ["/home/morten/.config/alacritty/tokyonight_moon.toml"]

[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font"


[window.dimensions]
optons_as_alt = "Both"
columns = 250
lines = 70

[window.padding]
x = 10
y = 10
