import = ["/home/morten/.config/alacritty/solarized_light.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Regluar"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regluar"

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 10
y = 10
