# Colors in RGB hex format

background = #272e33
foreground = #d2c6aa

second_hand = #ed8796

# Clock mode (analog or digital)
mode = digital

# Window dimensions
width = 164
height = 104

font = Comic Sans MS
