# Colors in RGB hex format

# Everforest Dark
background = #272e33
foreground = #d2c6aa

# Gruvbox Light
# background = #D7CAB6
# foreground = #3c3735

# Tokyo Night
# background = #24283b
# foreground = #c0caf5

# Atom One Light
# foreground = #383a42
# background = #fafafa

# Catppuccin Latte
# foreground = #1e66f5
# background = #eff1f5

# Catppuccin Mocha
# foreground = #cdd6f4
# background = #1e1e2e

second_hand = #ed8796

# Clock mode (analog or digital)
mode = digital

# Window dimensions
width = 164
height = 104

font = Comic Sans MS
