"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false

[cmd_duration]
disabled = true

[directory]
truncation_length = 6
style = "blue bold"
truncate_to_repo = false

[git_branch]
style = "bold green"

[golang]
disabled = true

[kubernetes]
format = '[$symbol$user( \($namespace\))]($style) in '
disabled = true
[kubernetes.user_aliases]
"mher.*cluster01.*" = "mher@cluster01"
"mher.*cluster02.*" = "mher@cluster02"
"mo.*skynet.*" = "morten@skynet"
