[cmd_duration]
disabled = true

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 6

[git_branch]
style = "green"

[kubernetes]
detect_env_vars = ["INVALID"]
detect_files = ["generator.yaml", "start.yaml", "start-environments.yaml", "start-replica.yaml"]
disabled = false
format = "[\\[$symbol$context/$namespace\\]]($style) "
style = "red"
[[kubernetes.contexts]]
context_alias = "$cluster"
context_pattern = ".*/api-(?P<cluster>\\w+).*"
