#!/usr/bin/env bash

if (grep "^monitor=,preferred,auto,1" ~/.config/hypr/hyprland.conf >>/dev/null); then
	sed -i "s/^monitor=,preferred,auto,1/#monitor=,preferred,auto,1"/ ~/.config/hypr/hyprland.conf
	sed -i "s/^#monitor=,2560x1440@240,0x0,1/monitor=,2560x1440@240,0x0,1"/ ~/.config/hypr/hyprland.conf
else
	sed -i "s/^#monitor=,preferred,auto,1/monitor=,preferred,auto,1"/ ~/.config/hypr/hyprland.conf
	sed -i "s/^monitor=,2560x1440@240,0x0,1/#monitor=,2560x1440@240,0x0,1"/ ~/.config/hypr/hyprland.conf
fi
