return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        branch = "main",
        lazy = false,
        cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
        config = function()
            require("nvim-treesitter").setup({
                -- Directory to install parsers and queries to
                install_dir = vim.fn.stdpath("data") .. "/site",
            })
            require("nvim-treesitter").install({
                "bash",
                "c",
                "comment",
                "diff",
                "dockerfile",
                "gitcommit",
                "go",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "html",
                "javascript",
                "jsdoc",
                "json",
                "jsonc",
                "lua",
                "luadoc",
                "luap",
                "make",
                "markdown",
                "markdown_inline",
                "nix",
                "nu",
                "printf",
                "python",
                "regex",
                "rego",
                "rust",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "zig",
            })
        end,
    },
}
