export LC_ALL=en_US.UTF-8

export EDITOR=nvim

export GOPATH=$HOME/Development/go

# Discard duplicates from both $PATH and $path
typeset -U PATH path
path=($GOPATH/bin $HOME/.emacs.d/bin $HOME/.local/bin /usr/local/go/bin $path)

