stty -ixon

bindkey -M viins '\e.' insert-last-word

source $HOME/.dotfiles/shell-aliases

eval "$(starship init zsh)"

eval "$(zoxide init --cmd cd zsh)"

eval "$(direnv hook zsh)"

source <(fzf --zsh)

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
