stty -ixon

HISTFILE="$HOME/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000
setopt appendhistory
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

eval "$(starship init zsh)"


zstyle :compinstall filename '~/.dotfiles/zsh/zshrc'

autoload -Uz compinit
compinit

source $HOME/.dotfiles/shell-aliases

source ~/.dotfiles/zsh/plugins/gojira/gojira.plugin.zsh
source ~/.dotfiles/zsh/plugins/mario/mario.plugin.zsh
source ~/.dotfiles/zsh/plugins/oc/oc.plugin.zsh
source ~/.dotfiles/zsh/plugins/history-substring-search/history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
