# Discard duplicates from both $PATH and $path
typeset -U PATH path

# PATH configuration must be in .zshrc (not .zshenv) because macOS runs
# /usr/libexec/path_helper from /etc/zprofile, which reorders PATH based on
# /etc/paths and /etc/paths.d/*. Since .zshenv runs before /etc/zprofile,
# any PATH changes there get overridden. Setting PATH here ensures our
# custom order (with /opt/homebrew/bin first) is preserved.
export PATH=$GOPATH/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.config/emacs/bin:/opt/homebrew/bin:$PATH

stty -ixon
autoload -Uz compinit
compinit

HISTSIZE=10000        # Number of commands to keep in memory during the session
SAVEHIST=10000        # Number of commands to save to the history file
HISTFILE=~/.zsh_history  # Where to save the history (this is the default)

bindkey -M viins '\e.' insert-last-word

source $HOME/.dotfiles/shell-aliases

eval "$(starship init zsh)"

eval "$(zoxide init zsh)"

eval "$(direnv hook zsh)"

source <(fzf --zsh)

if [[ "$(uname)" == "Darwin" ]]; then
  source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
else
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
fi

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
