#!/usr/bin/env bash

# Layout for Odyssey g9
# kitty tmux | kitty tmux layered with emacs gui | firefox

xdotool search --onlyvisible --name weechat \
  windowsize %1 1690 1410 windowmove %1 15 15

xdotool search --onlyvisible --name main \
  windowsize %1 1690 1410 windowmove %1 1720 15 \
  set_desktop_for_window %1 1

xdotool search --onlyvisible --class emacs \
  windowsize %1 1690 1410 windowmove %1 1720 15 \
  set_desktop_for_window %1 1

xdotool search --onlyvisible --class firefox \
  windowsize %1 1684 1410 windowmove %1 3425 15

xdotool key Super+1
