#!/bin/bash

nm-applet &
redshift &
picom -b --config ~/.config/picom/picom.conf &
dunst &
protonvpn-cli c -f &

kitty --title main tmux new-session -s main \; \
  new-window \; \
  new-window \; \
  new-window \; \
  move-window -s 4 -t 9 \; \
  rename-window vpn \; \
  split-window -v -t 0 \; \
  send-keys -t 0 'stibocon-reload' Enter \; \
  select-window -t 1 \; &

kitty --title weechat tmux new-session -s weechat \; \
  send-keys -t 0 'weechat' Enter \; &

emacs &
firefox &

sleep 1.5
~/.config/cwm/reset &
