#!/usr/bin/env bash

xrdb -remove && xrdb -cpp /usr/bin/cpp <~/.config/cwm/Xresources

# Input autorepeat
xset r rate 225 25
# Disable bell
xset b off

xsetroot -cursor_name left_ptr
xsetroot -solid "#252525"

# Fedora
[[ -f /usr/libexec/xdg-desktop-portal-gtk ]] && /usr/libexec/xdg-desktop-portal-gtk &

# Arch
[[ -f /usr/lib/xdg-desktop-portal-gtk ]] && /usr/lib/xdg-desktop-portal-gtk &

feh --bg-scale ~/Pictures/wallpaper/mountains-of-korea-3440x1440.png

blueman-applet &
picom -b --config ~/.config/cwm/picom.conf &
redshift -c ~/.config/cwm/redshift.conf &
dunst -conf ~/.config/cwm/dunstrc &
(sleep 10 && conky -c ~/.config/cwm/conky.conf &) &

exec cwm -c ~/.config/cwm/cwmrc
